Facturacion_Demo/Facturacion_Demo/Models/ErrorViewModel.cs
namespace Facturacion_Demo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Facturacion_Demo/Facturacion_Demo/Controllers/ComplementoPagoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Facturacion_Demo.Controllers
{
    public class ComplementoPagoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Facturacion_Demo/Facturacion_Demo/Controllers/HomeController.cs
using Facturacion_Demo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Facturacion_Demo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Facturacion_Demo/Facturacion_Demo/Views/ComplementoPago/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>
        Complemento de Pago
    </title>
</head>
<body>
    <div>
        <h2>Datos del Cliente</h2>
        <div class="d-inline-block">
            <label for="rfc" class="form-label">RFC</label>
            <input type="text" class="form-control w-auto" id="rfc" placeholder="RFC">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idRazonS" class="form-label">Nombre o Razon Social</label>
            <input type="text" class="form-control w-auto" id="idRazonS" placeholder="Nombre o Razon Social">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idCodigoP" class="form-label">Codigo Postal</label>
            <input type="text" class="form-control w-auto" id="idCodigoP" placeholder="Codigo Postal">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idRegimenF" class="form-label">Regimen Fiscal</label>
            <input type="text" class="form-control w-auto" id="idRegimenF" placeholder="Regimen Fiscal">
        </div>
    </div>
    <div>
        <h3>Concepto</h3>
        <div class="d-inline-block">
            <label for="idCiudad" class="form-label">Ciudad</label>
            <input type="text" class="form-control w-auto" id="idCiudad" placeholder="Ciudad">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idClaveP" class="form-label">Clave de Producto</label>
            <input type="text" class="form-control w-auto" id="idClaveP" placeholder="Clave de Producto">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idUnidad" class="form-label">Unidad</label>
            <input type="text" class="form-control w-auto" id="idUnidad" placeholder="Unidad">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idDescripcion" class="form-label">Descripcion de Unidad</label>
            <input type="text" class="form-control w-auto" id="idDescripcion" placeholder="Descripcion de Unidad">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idImporte" class="form-label">Importe</label>
            <input type="text" class="form-control w-auto" id="idImporte" placeholder="Importe">
        </div>
    </div>
    <div>
        <h4>Recepcion de Pago</h4>
        <div class="d-inline-block">
            <label for="" class="form-label">Fecha de Pago</label>
            <input type="text" class="form-control w-auto" id="" placeholder="Fecha de Pago">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idFormaP" class="form-label">Forma de Pago*</label>
            <input type="text" class="form-control w-auto" id="idFormaP*" placeholder="Forma de Pago*">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idMoneda" class="form-label">Moneda*</label>
            <input type="text" class="form-control w-auto" id="idMoneda" placeholder="Moneda*">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idTipoC" class="form-label">Tipo de Cambio</label>
            <input type="text" class="form-control w-auto" id="idTipoC" placeholder="Tipo de Cambio">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idMonto" class="form-label">Monto</label>
            <input type="text" class="form-control w-auto" id="idMonto" placeholder="Monto">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idNumeroO" class="form-label">Numero de Operacion*</label>
            <input type="text" class="form-control w-auto" id="idNumeroO" placeholder="Numero de Operacion*">
        </div>
    </div>
    <div>
        <h4>Busqueda de Factura</h4>
        <div class="d-inline-block">
            <label for="idBusquea" class="form-label">Busqueda por folio Fiscal</label>
            <input type="text" class="form-control w-auto" id="idBusquea" placeholder="Busqueda por folio Fiscal">
        </div>
    </div>
    <div class="text-center">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="btn btn-primary btn-lg">Buscar</a>
    </div>

</body>

</html>

Facturacion_Demo/Facturacion_Demo/Views/Factura/IndexFactura.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<html xmlns="http://www.w3.org/1999/xhtml">
    <head><title></title></head>
    <body>
    <div>
        <h4>Datos del emisor</h4>
        <div class="d-inline-block">
            <label for="rfc" class="form-label">RFC</label>
            <input type="text" class="form-control w-auto" id="rfc" placeholder="RFC">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idRazonS" class="form-label">Nombre o Razon Social</label>
            <input type="text" class="form-control w-auto" id="idRazonS" placeholder="Nombre o Razon Social">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idRegimenF" class="form-label">Regimen Fiscal</label>
            <input type="text" class="form-control w-auto" id="idRegimenF" placeholder="Regimen Fiscal">
        </div>
    </div>
    <div>
        <h4>Datos del receptor</h4>
        <div class="d-inline-block">
            <label for="rfc" class="form-label">RFC</label>
            <input type="text" class="form-control w-auto" id="rfc" placeholder="RFC">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idRazonS" class="form-label">Nombre o Razon Social</label>
            <input type="text" class="form-control w-auto" id="idRazonS" placeholder="Nombre o Razon Social">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="id_RecidenciaF" class="form-label">Residencia Fiscal</label>
            <input type="text" class="form-control w-auto" id="id_RecidenciaF" placeholder="Residencia Fiscal">
        </div>
        <div class="mb-3 d-inline-block">
            <label for="idRegimenF" class="form-label">Regimen Fiscal</label>
            <input type="text" class="form-control w-auto" id="idRegimenF" placeholder="Regimen Fiscal">
        </div>
    </div>
    <div class="text-center">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="btn btn-primary btn-lg">Guardar</a>
    </div>
    </body>
</html>

Facturacion_Demo/Facturacion_Demo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body text-center">
                <a asp-area="" asp-controller="Factura" asp-action="IndexFactura" class="btn btn-primary ">Facturacion</a>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body text-center">
                <a asp-area="" asp-controller="ComplementoPago" asp-action="Index" class="btn btn-primary ">Complemento de Pago</a>
            </div>
        </div>
    </div>
    <div class="col-sm-6 mt-3">
        <div class="card">
            <div class="card-body text-center">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="btn btn-primary ">Cancelaciones</a>
            </div>
        </div>
    </div>
</div>

Facturacion_Demo/Facturacion_Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Facturacion_Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Facturacion_Demo.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Facturacion_Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Facturacion_Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>